neo:
    hello: hello im dev update china2019-55555555
server:
  port: 8891
spring:
  application:
    name: business-client-test
eureka:                         #注册服务
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka