neo:
  Hello: hello im dev update china2019-55555555
server:
  port: 8891
spring:
  application:
    name: business-client-test
eureka:                         #注册服务
  client:
    serviceUrl:
      defaultZone: http://admin:111111@localhost:9000/eureka
# 负载均衡策略修改
BUSINESS-CLIENT-FEIGN:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
