neo:
    hello: hello im dev 32
spring:
  bus:
    trace:
      enabled: true
    enabled: true
management:                    #SpringCloud 1.5版本暴露接口，暴露/bus-refresh接口
  endpoints:                  #SpringCloud 2.0.0版本以后暴露接口方式
    web:
      exposure:
        include: bus-refresh
# 负载均衡策略修改
#BUSINESS-CLIENT-FEIGN:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
