neo:
  hello: hello im dev 50
spring:
  bus:
    trace:
      enabled: true
    enabled: true
  zipkin:
    base-url: http://localhost:9500,http://localhost:9501,http://localhost:9502
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
# 最后暴露自己的actuator的所有端口信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
# 负载均衡策略修改
#BUSINESS-CLIENT-FEIGN:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule