spring:
  application:
    name: cloud-zuul-server
  zipkin: # 对sleuth支持进行配置
    base-url: http://localhost:9500  # zipkin服务器地址
    sleuth:
      sampler:
        percentage: 1.0
# 添加断路器支持
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# 将com.netflix包的日志级别设为DEBUG。这样，Zuul就会打印转发的具体细节，从而帮助我们更好地理解Zuul的路由配置，生产环境关掉
logging:
  level:
    com.netflix: DEBUG
###############################################zuul重试开始#########################################################
# zuul重试
zuul:
  retryable: true #开启重试功能
  #全部服务忽略敏感头(全部服务都可以传递cookie)
  sensitive-headers:
  routes:
    # /myProduct/product/list -> /product/product/list
    aaaaaa:
      path: /myProduct/**
      serviceId: b2c-service-product
      sensitiveHeaders:
ribbon:
  # http建立socket超时时间,毫秒
  ConnectTimeout: 2000
  # http读取响应socket超时时间
  ReadTimeout: 8000
  # 同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 2
  # 重试负载均衡其他的实例最大重试次数,不包括首次server
  MaxAutoRetriesNextServer: 0
  # 是否所有操作都重试，POST请求注意多次提交错误。
  # 默认false，设定为false的话，只有get请求会重试
  OkToRetryOnAllOperations: true
###############################################zuul重试🔚############################################################
######>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#######
######>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#######
######>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#######
###############################################filter相关开始#########################################################
# 禁用指定的filter
#zuul:
#  FormBodyWrapperFilter:
#    pre:
#      disable: true
###############################################filter相关🔚########################################################
######>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#######
######>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#######
######>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#######
####################################################路由规则修改开始##################################################
####################################################1.自定义路由#####################################################
# 自定义微服务路由路径--简单写法，该写法可配置多个服务的映射
# 例如请求：http://127.0.0.1:8888/bbb/aaa/movie/user/zhangsan
# 就是请求zuul网关,网关根据自定义路由配置匹配，因为下面配置了/bbb/aaa/所以就把该请求转发到/bbb/aaa/对应的服务去处理
# 注意：1.自定义路径不覆盖默认映射，即:http://127.0.0.1:8888/business-client-zuul-b/movie/user/zhangsan依然请求会转发到该服务
# 2.自定义路径必须是完全匹配，比如http://127.0.0.1:8888/bbb/ccc/movie/user/zhangsan或者
# http://127.0.0.1:8888/bbb/movie/user/zhangsan都是不能匹配的
# 3.每个服务只能配置一个自定义路径
# zuul:
#   routes:
#     business-client-zuul-b: /bbb/aaa/**
# 自定义路径复杂写法--不推荐使用
#zuul:
#  routes:
#    #自定义路由名称，可随意命名
#    bbb:
#      #自定义路由路径，此为自定义访问路径
#      path: /movie/user/**
#      #自定义路由指向的服务Id
#      serviceId: business-client-zuul-b
#####################################################2.忽略某些服务############################################################
# 忽略某些服务--注意：忽略只忽略zuul的默认路由配置，并不会忽略自定义路由，生产环境应该把默认的按照服务名寻找路径都忽略掉，然后自定义路由路径
---
# zuul:
#   ignored-services: business-client-zuul-b
##################################################3.忽略所有微服务，只路由指定的微服务#############################################
# zuul:
#   ignored-services: '*'   # 使用'*'可忽略所有微服务
#   routes:
#     business-client-zuul-b: /bbb/ccc/**
##################################################4.同时指定微服务的serviceId和对应路径###########################################
# zuul:
#   routes:
#     b-route:                   # 该配置方式中，b-route只是给路由一个名称，可以任意起名。
#       service-id: business-client-zuul-b
#       path: /bbb/ccc/**           # service-id对应的路径
##################################################5.同时指定path和URL##########################################################
## 该种方式就是将某个IP-端口的微服务里面的所有服务都映射到/bbb/ccc/**路径下匹配
# zuul:
#   routes:
#     a-route:                   # 该配置方式中，a-route只是给路由一个名称，可以任意起名。
#       url: http://localhost:8881/ # 指定的url,一次只能指定一个
#       path: /bbb/ccc/**              # url对应的路径。
##################################################6.同时指定path和URL，并且不破坏Zuul的Hystrix、Ribbon特性########################
## 该种方式适合为某服务集群做映射
#zuul:
#  routes:
#    a-route:
#      path: /bbb/ccc/**
#      service-id: business-client-zuul-a
#  ribbon:
#    eureka:
#      enabled: false
#  business-client-zuul-a:
#    ribbon:
#      listOfServers: localhost:8881,localhost:8883
##################################################7.使用正则表达式指定Zuul的路由匹配规则##########################################
##################################################8.路由前缀###################################################################
##################################################9.忽略某些路径################################################################
## 该种方式用于将某些特殊的路径忽略代理，例如admin等管理员操作的路径
# zuul:
#   ignoredPatterns: /**/admin/**   # 忽略所有包含/admin/的路径
#   routes:
#     business-client-zuul-a: /bbb/ccc/user/**
####################################################路由规则修改🔚#############################################################