spring:
  application:
    name: business-client-consul-producer
  cloud:
    consul: #consul服务器的相关配置，本地采用Mac下安装的localhost服务器
      host: localhost
      port: 8500
      discovery:
        service-name: business-client-consul-producer #注册到consul的服务名称