spring:
  profiles:
    active:
      - secure
  zipkin:
    base-url: http://localhost:9500
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
# tag::configuration-eureka[]
---
#spring:
#  mail:
#    host: smtp.qq.com
#    username: 454205797@qq.com
#    password: #qq邮箱的授权码
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#            required: true
#          auth: true
#  boot:
#    admin:
#      notify:
#        mail:
#          to: 454205797@qq.com
---
spring:
  profiles: insecure
---
# admin登录的用户名和密码
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "admin"
# 2.0开始，actuator默认不开放，所以要设置为开放
management:
  endpoints:
    web:
      exposure:
        include: "*"  #暴露所有的端点我们可以看到更多应用相关信息
  endpoint:
    health:
      show-details: ALWAYS  #health endpoint是否必须显示全部细节