spring:
  application:
    name: business-client-jpa-thymeleaf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 111111
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: create
    show-sql: true
  thymeleaf:
    cache: false