spring:
  boot:
    admin:
      client:
        url: http://localhost:15601  # admin服务器地址
  zipkin:
    base-url: http://localhost:9500,http://localhost:9501,http://localhost:9502
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
# 最后暴露自己的actuator的所有端口信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS