spring:
  jackson: # jacson时间格式配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
###################################################################################################################
###################################                      基础设置            ######################################
###################################################################################################################
name: lzq2018010900065
workerId: 1     #工作机器ID(0~31)
datacenterId: 1 #数据中心ID(0~31)
# debug: true   #开启开发模式
# 切换日志配置文件
---
logging:
  config: classpath:log4j2.xml
###################################################################################################################
###################################                    spring配置            ######################################
################################################################################################################### 
spring:
  # 数据源及连接池配置--oracle
  #  datasource:
  #    driverClassName: oracle.jdbc.driver.OracleDriver
  #    url: jdbc:oracle:thin:@172.18.12.20:1521:orcl
  #    username: UMMP
  #    password: UMMP2019
  #    maxIdle: 10
  #    maxWait: 10000
  #    minIdle: 5
  #    initialSize: 5
  # 上传文件配置
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 20MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 20MB
# redis集群及连接池配置
#  redis:
#    cluster:
#      nodes: 172.18.12.21:7001,172.18.12.21:7002,172.18.12.22:7001,172.18.12.22:7002,172.18.12.23:7001,172.18.12.23:7002
#    password:
#    connection-timeout: 5000 #连接超时
#    so-timeout: 10000 #读写超时
#    max-attempts: 2 #重试次数
#    max-total: 20 #设置最大连接数
#    max-idle: 5 #设置最大空闲数
# MongoDB配置
#  data:
#    mongodb:
#      host: 172.18.12.23
#      port: 27017
#      database: log4j2
###################################################################################################################
###################################                   mybatis配置            ######################################
###################################################################################################################
# mybatis配置
---
mybatis:
  type-aliases-package: com.lzq.dto
  mapper-locations: classpath*:com/lzq/dao/*.xml
  configuration:
    cache-enabled: false #关闭缓存
    local-cache-scope: statement
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true  # mybatis下划线驼峰转换
###################################################################################################################
###################################                springcloud配置            #####################################
###################################################################################################################
# springcloud-ribbon组件配置--用于配置feign接口请求超时配置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  maxAutoRetries: 0
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
# 自动刷新配置（结合rabbitmq自动刷新配置-svn）
---
#spring:
#  cloud:
#    bus:
#      refresh:
#        enabled: true
#  rabbitmq:
#    password: guest
#    port: 5672
#    host: 127.0.0.1
#    username: guest
# springcloud-admin组件配置
---
#spring:
#  boot:
#    admin:
#      client:
#        username: admin
#        password: admin
#        url: http://127.0.0.1:15601
#        instance:
#          name: business-client-test
#          service-base-url: "http://localhost:10503"
#          prefer-ip: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节
###################################################################################################################
###################################                      其他配置            ######################################
###################################################################################################################   
# 文件上传保存路径配置
static:
  file:
    directory:
      name: static
    linux:
      url: /opt/lzq/uploadfile/${static.file.directory.name}
    windows:
      url: C:/${static.file.directory.name}
ummp:
  file:
    url: file/