spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9500,http://localhost:9501,http://localhost:9502
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1
girl: 18
logging:
  level:
    org.springframework.cloud.netflix.feign: debug
# 最后暴露自己的actuator的所有端口信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS